# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=fixroad


# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fixroad_db
spring.datasource.username=postgres
spring.datasource.password=12345


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# SERVER PORT CONFIGURATION
# ===============================
server.port=${PORT:8080}


# ===============================
# EMAIL (SMTP) CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fixroadservices@gmail.com
spring.mail.password=qcifepyfxmmlwqqi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# STATIC FILE STORAGE (UPLOADS)
# ===============================
spring.web.resources.static-locations=file:uploads/


# ===============================
# FILE UPLOAD SIZE LIMIT
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# ===============================
# TOMCAT FILE HANDLING CONFIG
# ===============================
server.tomcat.max-swallow-size=-1


# ===============================
# ERROR RESPONSE CONFIGURATION
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

jwt.secret=fixroad_super_secret_key_2026_secure